const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const closeCrops=async()=>{for(let i=0;i<6;i++){const hdr=[...document.querySelectorAll('*')].find(e=>e.childElementCount===0&&/Параметры изображения/.test(e.textContent)&&e.offsetParent!==null); if(!hdr) return; let d=hdr; for(let k=0;k<8&&d;k++){d=d.parentElement; const bt=d&&[...d.querySelectorAll('button')].find(x=>x.innerText.trim()==='Подтвердить'); if(bt){bt.click(); break;}} await sleep(1200);}};
const nb=[...document.querySelectorAll('button')].filter(b=>{const r=b.getBoundingClientRect();return r.top<200&&r.top>40&&r.left<300&&r.height>0&&b.className.includes('el-tooltip__trigger')&&!b.className.includes('favorite')&&!b.className.includes('ai-select')}); nb[0].click(); await sleep(2500);
if(!/Veo 3\.1 Lite/.test(document.body.innerText)) throw new Error('not Lite');
const b=await fetch(`https://raw.githubusercontent.com/contentmakerliza-art/eink-roliki/frames/f/hook${N}_start.jpg`).then(r=>r.blob());
for(const name of ['start.jpg','end.jpg']){const inp=document.querySelector('input[type=file]'); const dt=new DataTransfer(); dt.items.add(new File([b],name,{type:'image/jpeg'})); inp.files=dt.files; inp.dispatchEvent(new Event('change',{bubbles:true})); await sleep(2500); await closeCrops();}
await sleep(1000); await closeCrops();
const p="Realistic vertical smartphone video, UGC style. The first and last frames are the provided images: a woman's hand holds a phone case with a small rectangular e-ink panel on the back, an iPhone with pink camera module is inside the case, light wooden table, soft daylight. Action: the hand gently tilts the phone only slightly, at most 20 degrees to the left, then at most 20 degrees to the right, the glossy edge of the case catches the light, then it returns exactly to the starting position facing the camera. Small subtle rotation only: the phone NEVER turns sideways or edge-on, the side of the phone is never seen straight on, the back with the camera module and the e-ink panel stays fully visible at all times, the phone is always physically inside the case. The e-ink panel shows exactly what it shows in the image and does not change, nothing new appears on it, no glow. Gentle slow push-in. Keep the phone, case color and camera module exactly as in the images. No text, no logos, no speech, no music.";
const ta=document.querySelector('textarea'); Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(ta,p); ta.dispatchEvent(new Event('input',{bubbles:true})); await sleep(800);
const L=document.body.innerText.split('\n').map(s=>s.trim()).filter(Boolean); const i=L.findIndex(l=>/^Google Veo - /.test(l)); const n=[...document.querySelectorAll('img')].filter(im=>{const r=im.getBoundingClientRect();return r.width>40&&r.width<200}).length;
let res; if(L[i-1]!=='0'||n<2) res={abort:true,price:L[i-1],n}; else { document.querySelector('.send-actions__send').click(); await sleep(4000); res={ok:true,url:location.pathname,limit:/limit reached/i.test(document.body.innerText)}; } return res;
